teleop:
  move_axis:
    type: topic
    message_type: geometry_msgs/TwistStamped
    topic_name: /iiwa/command/CartesianVelocity
    deadman_buttons: [5]     # R1 per muovere
    axis_mappings:
      - axis: 0
        target: twist.linear.x
        scale: 1000
      -
        axis: 1
        target: twist.linear.y
        scale: 1000

      - axis: 4
        target: twist.linear.z
        scale: 1000

  close_gripper:
    type: service
    service_name: /iiwa/configuration/openGripper
    service_request:
      open: false
    service_persistent: False
    buttons: [ 0 ]


  open_gripper:
    type: service
    service_name: /iiwa/configuration/openGripper
    service_request:
      open: true
    service_persistent: False
    buttons: [ 1 ]
