teleop:

  # normal speed
  move_axis_linear:
    type: topic
    message_type: geometry_msgs/TwistStamped
    topic_name: /iiwa/command/CartesianVelocity
    deadman_buttons: [5]     # R1
    axis_mappings:
      - axis: 0
        target: twist.linear.x
        scale: -1000
      -
        axis: 1
        target: twist.linear.y
        scale: 1000

      - axis: 4
        target: twist.linear.z
        scale: 1000


  move_axis_angular:
    type: topic
    message_type: geometry_msgs/TwistStamped
    topic_name: /iiwa/command/CartesianVelocity
    deadman_buttons: [ 4 ]     # L1
    axis_mappings:
      - axis: 0
        target: twist.angular.x
        scale: 2

      - axis: 1
        target: twist.angular.y
        scale: 2

      - axis: 4
        target: twist.angular.z
        scale: 2

  # slow
  move_axis_linear_slow:
    type: topic
    message_type: geometry_msgs/TwistStamped
    topic_name: /iiwa/command/CartesianVelocity
    deadman_buttons: [ 7 ]     # R2
    axis_mappings:
      - axis: 0
        target: twist.linear.x
        scale: -100
      - axis: 1
        target: twist.linear.y
        scale: 100

      - axis: 4
        target: twist.linear.z
        scale: 100


  # services
  close_gripper:
    type: service
    service_name: /iiwa/configuration/openGripper
    service_request:
      open: false
    service_persistent: True
    buttons: [ 0 ]


  open_gripper:
    type: service
    service_name: /iiwa/configuration/openGripper
    service_request:
      open: true
    service_persistent: True
    buttons: [ 1 ]
