joint_position: 
    - a1: 0.875962078571
    - a2: 0.991766989231
    - a3: 1.07567560673
    - a4: -1.12447535992
    - a5: -0.836169660091
    - a6: 1.44788885117
    - a7: 1.80269372463


cartesian_pose:
    - position:
        - x: 0
        - y: 0.656374830045
        - z: 0.09614097396 

    - orientation:
        - x: 0
        - y: 1
        - z: 0
        - w: 0
