joint_position: 
    - a1: 1.0815871954
    - a2: 0.533782601357
    - a3: -0.633643329144
    - a4: -1.61988711357
    - a5: 0.321300804615
    - a6: 1.09286999702
    - a7: 0.364907056093

cartesian_pose:
    - position:
        - x: 0 
        - y: 0.30934015617
        - z: 0.09614097396 

    - orientation:
        - x: 0
        - y: 1
        - z: 0
        - w: 0
